### PR TITLE
Add template for performance spreadsheets

### PR DESCRIPTION
**Pull request by sadielbartholomew**
Uploads the template spreadsheet from which the final per-machine performance spreadsheets will be created by means of customisation in appropriate places (as indicated by `<placeholder text>`) using `openpyxl` and the CVs, etc., to be seeded for each machine documented by each institute.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
@davidhassell the set up of the template added here should support the final approach as we discussed last week (no sub-component input item, one tab per realm, etc.). Please can you take a look to check it is as you imagined (or, we can review this as a group in this week's Telco)? Note that there is only one input tab on the template because the code to generate the final spreadsheets will copy that tab and customise appropriately, but for the final product there will be N tabs for each model where N is the number of applicable realms for that model.

**Comment by davidhassell** [comment]
Hi @sadielbartholomew. Looks good. I have a few of minor suggestions/questions:

* The realm name should not be an option - i.e. remove **1.1.2** (but store the realm name in a "hidden" cell, perhaps)
* I presume that there'll be a "toplevel" tab, too.
* Some of the descriptions are summaries of the those in the CIM - probably better to copy the CIM property descriptions verbatim.

Thanks, David

**Comment by sadielbartholomew** [comment]
Thanks for the comments @davidhassell. It sounds like I might have misunderstood some aspects of our conversations, especially RE top-level tabs, so it would be good to clarify what I did not get (quite or otherwise) right! In response:

> The realm name should not be an option

True, and I remember us covering this, but equally the 'model' and the 'platform' items are fixed for each tab so should not be changed either, yet they are available as effective question items that are pre-populated even though, indeed, a user might not realise and interfere with them.

So it is a wider issue than just for the realm item, so perhaps we need to address all three of those in this respect? But, if so, I am not sure storing in hidden cells is a good idea because having those viewable and known as important values helps to clarify the nature of the tab (they are also incorporated in the 'name' item, as you can see from the template here, but that alone doesn't make it 100% clear IMO). Also in terms of parsing the spreadsheet back in, it will be less clean and robust with a hidden item and there is the risk that a user deletes the hidden cell without knowing it holds that important piece of info.

I will check with Mark as to potential approaches for this, though if we don't have any other ideas, I would think having those items as normal questions, as they are, but greying them out in terms of the font and background colour to indicate they shouldn't be touched, and explaining so in the front page notes, would work well?

> I presume that there'll be a "toplevel" tab, too.

Please can you clarify; do you mean a top-level tab for each model to cover values potentially shared across all of the realms? I seem to recall asking about whether we needed that form of top-level tab and, as I understood it, you implied that it would not make much sense to have one because each of the realms are so distinct including in terms of performance metrics? Did I get that wrong? Sorry if so.

> Some of the descriptions are summaries of the those in the CIM - probably better to copy the CIM property descriptions verbatim.

Well spotted, thanks. I realise now I forgot to check they were identical to the CIM v2.2 when waiting on updates to ES-DOC/esdoc-cim-v2-schema#45. I'll update the template in a new commit so that the property descriptions are identical to those specified in the CIM.

**Comment by davidhassell** [comment]
Hi @sadielbartholomew,

> ... but equally the 'model' and the 'platform' items are fixed for each tab ....

Good point. Your suggestion sounds fine to me. 

> Please can you clarify; do you mean a top-level tab for each model to cover values potentially shared across all of the realms?

I think we need a toplevel tab for storing the performance of the model as a whole, i.e. the _aggregate_ performance of all of the realms. E.g. if a model has two realms: atmos and land surface with respective performances of 10 simulated years per real day and 20  simulated years per real day, then the toplevel performance might be something like 30 simulated years per real day (assuming for the purposes of this example that  the sub-components were run in serially). This toplevel tab would ultimately link to a `science.model`, where as the sub-component tabs will ultimately link to a `science.realm`.

Hope that helps!

**Comment by sadielbartholomew** [comment]
> Hope that helps!

It does indeed, thanks David. Corresponding updates to come in a few new commits that I will push shortly...

**Comment by sadielbartholomew** [comment]
Thanks again for the feedback, @davidhassell.

When you get a chance, it would be useful if you could confirm if the changes made in the new commits have addressed your points, then we can merge this, otherwise I can adapt the template further. (I have code nearly ready to seed the final performance spreadsheets from this template given certain relevant info. from the machine documents, but I will put that up as a separate PR at a future date since the machine publication etc. is higher priority so will be done first.)

**Comment by davidhassell** [comment]
Hi Sadie, this version looks good to me - nice work.

**Comment by sadielbartholomew** [comment]
Thanks David, I'll merge it in that case.

**Pull request merged**
