### PR TITLE
Experiment validation for performance spreadsheets

### PR DESCRIPTION
**Pull request by sadielbartholomew**
Update the performance template spreadsheet to allow the institutions to change the applicable experiments to each performance supplied from the ones they specified to apply generically for the machine in the corresponding machine spreadsheet from which the performance spreadsheet will be seeded. Changes made in response to further feedback from @davidhassell.

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
@davidhassell please note I haven't added the full drop-down list of possible CMIP6 experiments to the template, just marked as a comment in the appropriate cells that should would contain that ("<example enum list of all experiments provided in any of the questions of 1.9.2 (i.e. for all MIPs) in the machine spreadsheet>") since it is easier to do that as part of the spreadsheet customisation (`openpyxl` code) stage. And note also, though I have only put a single cell for the template, the `openpyxl` code will process in as many of those rows to state (as a selection on copies of that drop-down list) all experiments enumerated in the corresponding machine spreadsheet, one after the other, as I believe we agreed upon last week.

**Comment by sadielbartholomew** [comment]
Hi @davidhassell, this is still open from way back. If you (quite understandably) can't remember the context to the PR by now, then feel free to ask me on Slack or in the Telco tomorrow, or otherwise...

**Comment by davidhassell** [comment]
Hi Sadie,

Nice. A question and a comment:

* Dark grey boxes (`1.1.[1234]`): I presume that these will be pre-populated?

> NOTE: you should provide a performance to cover all experiments applicable to this machine, model and realm(s) in this spreadsheet. Experiments not covered in this performance tab should be documented elsewhere, either in groups or individually, such that across the spreadsheet all experiments will be represented in some tab for the given model and realm(s).

This is right, but I found that it a little confusing in this context, thinking that we should restrict notes here to just _this_ performance doc. Perhaps this paragraph should be in the guidance on the ES-DOC website instead?

**Comment by sadielbartholomew** [comment]
Thanks for your feedback, David.

> This is right, but I found that it a little confusing in this context, thinking that we should restrict notes here to just this performance doc. Perhaps this paragraph should be in the guidance on the ES-DOC website instead?

I agree that cross-document notes belong in the general guidance rather than inside the document, but I think, based on your comment, that the quoted text I wrote is definitely *not clear* and indeed confusing, because your interpretation of it here is not what I intended.

Namely, what I was hoping to convey with that paragraph pertains only to the given performance document i.e. spreadsheet, in that I was trying to emphasise that *each experiment applicable to the machine (the one covered by the spreadsheet), model and realm(s) (in both cases to cover all of those applicable given the institute-specified models and realms per experiment) should be documented in one of the tabs in the filled-out spreadsheet, i.e. none should be missed out on that performance document*. Or, in short, that *all experiments listed in the drop-down list 1.1.5.1 should be addressed in one of the tabs for a spreadsheet to be considered complete* (OK, this sounds like a clearer way to describe it, in hindsight).

Does that make sense? If not, sorry - maybe we can chat about it in the imminent Telco, or otherwise?

**Comment by sadielbartholomew** [comment]
Discussed externally - we agreed that, as reflected by the number of guidance notes required in the spreadsheet, there are probably too many tabs per spreadsheet resulting from our current structuring plans, so we will change tack and move to having **one spreadsheet per machine and given model** (so for every machine, there will be *N* spreadsheets covering the *N* applicable models) rather than **one per machine to cover all models applicable to that machine**.

I will merge this as a first step, because bar from wanting to change the structure as above, which will necessarily mean amending the guidance notes, and removing such notes as that raised in https://github.com/ES-DOC/cmip6/pull/9#issuecomment-960564185, the template spreadsheet is ready, hence is a better comparison point for the final PR (which will implement the structuring change) than the state of the spreadsheet before this PR.

***

@davidhassell, FYI sorry I missed the question along with the comment:

> Dark grey boxes (1.1.[1234]): I presume that these will be pre-populated?

Yes, indeed. I try to imply that for these templates by writing inside `<` and `>` characters (as '<description of info to inject>').

**Pull request merged**
