### PR TITLE
Update template towards per-model performance spreadsheets

### PR DESCRIPTION
**Pull request by sadielbartholomew**
Update the performance template spreadsheet in line with my comment from https://github.com/ES-DOC/cmip6/pull/9#issuecomment-961330517 summarising our agreed change in approach:

> we will change tack and move to having one spreadsheet per machine and given model (so for every machine, there will be N spreadsheets covering the N applicable models) rather than one per machine to cover all models applicable to that machine.

Visually, the number and form of spreadsheets to be generated using this one template for a given institute will be as follows, where N indicates the final applicable model for each machine and M the final machine:

```bash
├── Institute X
        ├───Machine 1
        │     ├───Model A1 ──> spreadsheet 1-A1
        │     ├───Model B1 ──> spreadsheet 1-B1
        │     ├───...
        │     └───Model N1 ──> spreadsheet 1-N1
        │
        ├───Machine 2
        │     ├───Model A2 ──> spreadsheet 2-A2
        │     ├───Model B2 ──> spreadsheet 2-B2
        │     ├───...
        │     └───Model N2 ──> spreadsheet 2-N2
        │
        ├───...
        │
        ├───Machine M
              ├───Model AN ──> spreadsheet M-AM
              ├───Model BN ──> spreadsheet M-BM
              ├───...
              └───Model NM ──> spreadsheet M-NM
```

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
(Sorry, ended up doing two force pushes because I was working on a branch that didn't have the merge of the latest performance template PR which caused havoc with sync'ing to master - I don't trust merging, rebasing and conflict resolution when I can't see an explicit `diff`, as with the spreadsheet format.)

**Review by davidhassell — CHANGES_REQUESTED** [review]
#### Applicable experiments

list all of the experiments **to** which this performance applies ~to~, where the list of potential choices is the list of all experiments for CMIP6 and the pre-populated answers, which may be edited, are drawn from the answers you provided to the ‘applicable experiments by MIP’ questions in the spreadsheet you submitted for this machine **.** ~?~

For the realm tabs, perhaps include a 1.1.5 row that needs nothing entered, but says something like "Applies to all experiments specified by the aggregate performance for \<model name\>"

**Comment by sadielbartholomew** [comment]
Thanks for the feedback, David, which all sound sensible (the latter will make things clearer). I'll get your suggestions added in a new commit.

**Comment by sadielbartholomew** [comment]
I believe I have addressed both of your points now, @davidhassell. Please go ahead and re-review.

**Review by davidhassell — CHANGES_REQUESTED** [review]
Hi Sadie - looks good. Perhaps miss out the `Not applicable, ` of the new grey box in the realm's 1.1.5. Seems a bit odd when the experiments are applicable!  I'm otherwise happy - please merge.

**Comment by sadielbartholomew** [comment]
> Perhaps miss out the Not applicable, of the new grey box in the realm's 1.1.5. Seems a bit odd when the experiments are applicable!

Very good point! I was trying to convey that the question wasn't applicable in the realm tabs cases but I'm glad you noticed what I didn't in that it could easily be very confusing. Will remove and then merge. Thanks.

**Pull request merged**
